services:
  postgres:
    image: postgres:16
    container_name: app_postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: ./backend
      dockerfile: Api/Dockerfile.dev
    container_name: app_api
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}

      # EF Core
      ConnectionStrings__Default: Host=postgres;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}

      # JWT
      Jwt__Issuer: ${JWT_ISSUER}
      Jwt__Audience: ${JWT_AUDIENCE}
      Jwt__SigningKey: ${JWT_SIGNING_KEY}
      Jwt__ExpiresMinutes: ${JWT_EXPIRES_MINUTES}

      # Hot reload fiable dans Docker
      DOTNET_USE_POLLING_FILE_WATCHER: "1"
    ports:
      - "${API_PORT}:8080"
    volumes:
      - ./backend:/src
      - nuget_cache:/root/.nuget/packages
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: app_frontend
    depends_on:
      - api
    environment:
      VITE_API_BASE_URL: http://localhost:${API_PORT}
      CHOKIDAR_USEPOLLING: "true"
      CHOKIDAR_INTERVAL: "250"
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules

volumes:
  pgdata:
  nuget_cache:
  node_modules: